---
baseURL: http://docs.netgain-systems.com
title: NetGain Docs
theme: hugo-geekdoc
copyRight: 'NetGain Systems (c) 2002-2020. All rights reserved.'
myvar: 'dd'
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/netgainsystems
  geekdocEditPath: blob/master/content

  #geekdocLogo: logo.png

  geekdocSearch: true

  geekdocLegalNotice: https://www.netgain-systems.com/legal
  geekdocPrivacyPolicy: https://www.netgain-systems.com/privacy
